ChristianPerez34/lifeline_crypto_tbot

- .vscode/settings.json
- lifeline_crypto_tbot.py
- poetry.lock
- pyproject.toml
Basic telegram bot that echoes messages to user
Closes #1
> Basic telegram bot.

- lifeline_crypto_tbot.py
Added telegram bot to group. 
Closes #4
> Add telegram to group

- .vscode/settings.json
- lifeline_crypto_tbot.py
Greets new users in the telegram group.
> Added handler that automatically greets new users

- handler/base.py
- handler/crypto.py
- lifeline_crypto_tbot.py
> Added bot command to display trending coins

- handler/base.py
- handler/crypto.py
- lifeline_crypto_tbot.py
Bot is able to start a scheduler based on a limit price the user sets. Once limit price is reached, bot will send a message out reminding the group.
Format:
/alert [COIN] [SIGN] [PRICE]
> Crypto Price Alert

- handler/base.py
- handler/crypto.py
- lifeline_crypto_tbot.py
- poetry.lock
- pyproject.toml
> Added bot command to display latest crypto listings.

- handler/crypto.py
> Added latest listings for CoinMarketCap

- bot/kucoin_bot.py
- handler/crypto.py
> Bot alerts on position updates for take profit and stop loss

- handlers/__init__.py
- handlers/crypto.py
> Updates to coin lookup 

- handlers/base.py
- handlers/crypto.py
Modified sell coins feature to sell percentage of coins
> RE-worked sell coins feature 

- bot/kucoin_bot.py
> Added PNL for closed KuCoin futures positions

- bot/kucoin_bot.py
> Fixed bug with KuCoin Futures Contracts

- bot/kucoin_bot.py
- handlers/crypto.py
> Fixed bug with KuCoin signals

- api/bsc.py
- config.py
- handlers/crypto.py
Exception handling for buy coin command
Closes #83
> Created pancakeswap api wrapper.

- api/coinmarketcap.py
- config.py
- handlers/crypto.py
> Updated trending coins command to include CMC trending coins

- app/lifeline_crypto_tbot.py
- handlers/crypto.py
- models.py
> Created model to store alerts in DB

- api/bsc.py
- app/lifeline_crypto_tbot.py
- handlers/crypto.py
- poetry.lock
- pyproject.toml
> Bsc account balance

- app/lifeline_crypto_tbot.py
- bot/kucoin_bot.py
- handlers/base.py
- handlers/crypto.py
- handlers/user.py
- utils.py
> Handled a few issues found by deepsource app

- handlers/crypto.py
- handlers/user.py
- poetry.lock
- pyproject.toml
- schemas.py
> Basic Pydantic Validation

- api/bsc.py
- api/coingecko.py
- api/coinmarketcap.py
- api/kucoin.py
- app/lifeline_crypto_tbot.py
- handlers/base.py
- handlers/crypto.py
- handlers/user.py
> Logging and documentation

- api/bsc.py
- api/coingecko.py
- api/coinmarketcap.py
- api/kucoin.py
- app/lifeline_crypto_tbot.py
- bot/kucoin_bot.py
- config.py
- handlers/__init__.py
- handlers/crypto.py
- handlers/user.py
- schemas.py
> Fixed issue with displaying user account balance

- api/bsc.py
- app/lifeline_crypto_tbot.py
- handlers/base.py
- handlers/crypto.py
- schemas.py
> Added command to peek at some of a user's address holdings

- handlers/crypto.py
> Fixed bug when inputting price alert with commas

- api/bsc.py
- handlers/base.py
- handlers/crypto.py
- poetry.lock
- schemas.py
> Able to lookup coin price info via PancakeSwap. Updated help text.

- config.py
- handlers/base.py
> Added random greetings

- abi/pancake_swap_liquidity_v2.abi
- api/bsc.py
- app/lifeline_crypto_tbot.py
- bot/bsc_sniper.py
- handlers/base.py
- handlers/crypto.py
- schemas.py
> PancakeSwap token sniping

- api/bsc.py
- bot/bsc_sniper.py
Sniping utilizes higher gas prices to ensure successful token buy
Closes #154
> Able to buy tokens that require fee on swap. 

- api/bsc.py
- app/lifeline_crypto_tbot.py
- handlers/base.py
- handlers/crypto.py
Closes #160 
Also increased sniping gas price to 65 gwei
> Renamed coin command to price

- handlers/crypto.py
> Modified Spy command to display data in Table format

- api/bsc.py
- app/lifeline_crypto_tbot.py
- handlers/__init__.py
- handlers/crypto.py
- handlers/user.py
- models.py
- poetry.lock
- pyproject.toml
- schemas.py
Trying to make structure a lots more easygoing for when more chains are added 
Closes #144
> Restructured DB

- api/bsc.py
- api/coingecko.py
- api/coinmarketcap.py
- api/kucoin.py
- app/__init__.py
- app/lifeline_crypto_tbot.py
- bot/bsc_order.py
- bot/bsc_sniper.py
- bot/kucoin_bot.py
- config.py
- handlers/__init__.py
- handlers/base.py
- handlers/crypto.py
- handlers/error.py
- handlers/user.py
- models.py
- schemas.py
> Untested version of limit orders on pancake swap

- api/bsc.py
- app/lifeline_crypto_tbot.py
- bot/bsc_order.py
- handlers/base.py
- handlers/crypto.py
- models.py
> Able to cancel orders

- api/bsc.py
- handlers/crypto.py
> Added token name and token symbol to order dataframe

- api/eth.py
- api/matic.py
- config.py
- handlers/__init__.py
- handlers/base.py
- handlers/crypto.py
- handlers/user.py
- models.py
- schemas.py
Able to register and view balances of MATIC & ETH wallet addresses
CLoses #183
> MATIC and ETH balance integration

- api/bsc.py
- api/eth.py
- api/matic.py
- bot/bsc_order.py
- handlers/crypto.py
- models.py
- schemas.py
> Should be able to swap on ethereum, polygon and bsc. Untested!

- ReadMe.md
- api/bsc.py
- api/eth.py
- handlers/base.py
- handlers/crypto.py
> Fixed bug with selling tokens. Added ReadMe

- api/bsc.py
- handlers/crypto.py
> Added message when token not found in CG nor CMC

- api/bsc.py
- api/eth.py
- api/matic.py
> Pre-approve tokens for swapping

- app/__init__.py
- app/lifeline_crypto_tbot.py
- handlers/crypto.py
- pyproject.toml
Added inline query for chart command.
Planning on doing the same with the candle chart feature. Will probably due it when more interest on this command arises. 
With the inline query, users can choose which token to view charting data.
> Chart inline query

- config.py
- handlers/base.py
- handlers/user.py
- models.py
- pyproject.toml
- schemas.py
Users can only register their CoinBase Pro API keys at the moment. Further down the line users will be able to execute different operations:
- Executing Trades
- Viewing balance
Closes #215
> Allows users to register their CoinBase Pro API keys with bot

- api/bsc.py
- api/coinbase.py
- api/eth.py
- api/matic.py
- handlers/base.py
- handlers/crypto.py
- schemas.py
> Users able to view coinbase account holdings via balance command

- handlers/crypto.py
> Price command should display correct messages when token not found

- api/bsc.py
- api/eth.py
- api/matic.py
- config.py
- pyproject.toml
> Introduced aiofiles for aync file operations

- Dockerfile
- api/coinbase.py
- api/coinpaprika.py
- api/cryptocompare.py
> Coinbase balance command bug fix
